#!/usr/bin/env python3
"""
Generate Markdown files with frontmatter from extracted PDF text.
Maps each PDF filename to regulation metadata.
"""

import os
import re
import json
from pathlib import Path

# Regulation metadata mapping: filename -> metadata
# Each entry: (slug, jenis, nomor, title, tahun, tanggal_diundangkan, tanggal_berlaku, status, topik, sektor, berlaku_untuk, ringkasan, mencabut, dicabut_oleh, mengubah, diubah_oleh, dasar_hukum)
REGULATIONS = [
    {
        "file": "122_PMK.03_2019Per.pdf",
        "slug": "pmk/pmk-122-2019",
        "jenis": "PMK",
        "nomor": "PMK-122/PMK.03/2019",
        "title": "Tata Cara Pengenaan Pajak Bumi dan Bangunan Sektor Pertambangan Minyak dan Gas Bumi",
        "tahun": 2019,
        "tanggal_diundangkan": "2019-09-05",
        "tanggal_berlaku": "2020-01-01",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "migas", "minyak", "gas bumi", "pengenaan"],
        "sektor": ["pertambangan_migas"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan minyak dan gas bumi.",
    },
    {
        "file": "2024pmkeuangan081.pdf",
        "slug": "pmk/pmk-81-2024",
        "jenis": "PMK",
        "nomor": "PMK-81/PMK.03/2024",
        "title": "Ketentuan Perpajakan dalam rangka Pelaksanaan Sistem Inti Administrasi Perpajakan (Coretax)",
        "tahun": 2024,
        "tanggal_diundangkan": "2024-10-14",
        "tanggal_berlaku": "2025-01-01",
        "status": "berlaku",
        "topik": ["coretax", "administrasi", "perpajakan", "sistem inti"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB", "PPh", "PPN"],
        "ringkasan": "Mengatur ketentuan perpajakan dalam rangka pelaksanaan Sistem Inti Administrasi Perpajakan (Coretax).",
    },
    {
        "file": "2024pmkeuangan118.pdf",
        "slug": "pmk/pmk-118-2024",
        "jenis": "PMK",
        "nomor": "PMK-118/PMK.03/2024",
        "title": "Perubahan atas PMK-81/PMK.03/2024 tentang Ketentuan Perpajakan Coretax",
        "tahun": 2024,
        "tanggal_diundangkan": "2024-12-31",
        "tanggal_berlaku": "2025-01-01",
        "status": "berlaku",
        "topik": ["coretax", "administrasi", "perpajakan", "perubahan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB", "PPh", "PPN"],
        "mengubah": "PMK-81/PMK.03/2024",
        "ringkasan": "Perubahan atas PMK-81/PMK.03/2024 tentang Ketentuan Perpajakan dalam rangka Pelaksanaan Coretax.",
    },
    {
        "file": "2025pmkeuangan015.pdf",
        "slug": "pmk/pmk-15-2025",
        "jenis": "PMK",
        "nomor": "PMK-15/PMK.03/2025",
        "title": "Perubahan Kedua atas PMK-81/PMK.03/2024 tentang Ketentuan Perpajakan Coretax",
        "tahun": 2025,
        "tanggal_diundangkan": "2025-02-04",
        "tanggal_berlaku": "2025-02-04",
        "status": "berlaku",
        "topik": ["coretax", "administrasi", "perpajakan", "perubahan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB", "PPh", "PPN"],
        "mengubah": "PMK-81/PMK.03/2024",
        "ringkasan": "Perubahan kedua atas PMK-81/PMK.03/2024 tentang Ketentuan Perpajakan dalam rangka Pelaksanaan Coretax.",
    },
    {
        "file": "48_PMK.03_2021Per_opt.pdf",
        "slug": "pmk/pmk-48-2021",
        "jenis": "PMK",
        "nomor": "PMK-48/PMK.03/2021",
        "title": "Tata Cara Pendaftaran, Pelaporan, dan Pendataan Objek Pajak PBB",
        "tahun": 2021,
        "tanggal_diundangkan": "2021-05-25",
        "tanggal_berlaku": "2021-07-01",
        "status": "berlaku",
        "topik": ["PBB", "pendaftaran", "pelaporan", "pendataan", "objek pajak"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pendaftaran, pelaporan, dan pendataan objek pajak Pajak Bumi dan Bangunan.",
    },
    {
        "file": "67_PMK.03_2020Per.pdf",
        "slug": "pmk/pmk-67-2020",
        "jenis": "PMK",
        "nomor": "PMK-67/PMK.03/2020",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Panas Bumi",
        "tahun": 2020,
        "tanggal_diundangkan": "2020-06-30",
        "tanggal_berlaku": "2020-08-01",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "panas bumi", "pengenaan"],
        "sektor": ["panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan panas bumi.",
    },
    {
        "file": "78-PMK.03-2016 ttg Tata Cara Penerbitan STP PBB.pdf",
        "slug": "pmk/pmk-78-2016",
        "jenis": "PMK",
        "nomor": "PMK-78/PMK.03/2016",
        "title": "Tata Cara Penerbitan Surat Tagihan Pajak PBB",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-04-29",
        "tanggal_berlaku": "2016-06-01",
        "status": "berlaku",
        "topik": ["PBB", "STP", "surat tagihan", "penerbitan", "penagihan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara penerbitan Surat Tagihan Pajak (STP) Pajak Bumi dan Bangunan.",
    },
    {
        "file": "81-PMK.03-2017.pdf",
        "slug": "pmk/pmk-81-2017",
        "jenis": "PMK",
        "nomor": "PMK-81/PMK.03/2017",
        "title": "Pengurangan Denda Administrasi PBB dan Pengurangan atau Pembatalan SPPT, SKP PBB, STP PBB yang Tidak Benar",
        "tahun": 2017,
        "tanggal_diundangkan": "2017-06-12",
        "tanggal_berlaku": "2017-07-13",
        "status": "berlaku",
        "topik": ["PBB", "pengurangan", "denda", "pembatalan", "SPPT", "SKP", "STP"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur pengurangan denda administrasi PBB dan pengurangan atau pembatalan SPPT, SKP PBB, STP PBB yang tidak benar.",
    },
    {
        "file": "82-PMK.03-2017.pdf",
        "slug": "pmk/pmk-82-2017",
        "jenis": "PMK",
        "nomor": "PMK-82/PMK.03/2017",
        "title": "Pemberian Pengurangan PBB",
        "tahun": 2017,
        "tanggal_diundangkan": "2017-06-12",
        "tanggal_berlaku": "2017-07-13",
        "status": "berlaku",
        "topik": ["PBB", "pengurangan", "fasilitas"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur pemberian pengurangan Pajak Bumi dan Bangunan.",
    },
    {
        "file": "83_kmk.04_2000.pdf",
        "slug": "kmk/kmk-83-2000",
        "jenis": "KMK",
        "nomor": "KMK-83/KMK.04/2000",
        "title": "Pembagian dan Penggunaan Biaya Pemungutan PBB",
        "tahun": 2000,
        "tanggal_diundangkan": "2000-03-17",
        "tanggal_berlaku": "2000-03-17",
        "status": "berlaku",
        "topik": ["PBB", "biaya pemungutan", "pembagian"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur pembagian dan penggunaan biaya pemungutan Pajak Bumi dan Bangunan.",
    },
    {
        "file": "KEP - 25.PJ.2016 ttg Penetapan Nilai Bumi Sektor Hutan.pdf",
        "slug": "kep/kep-25-2016",
        "jenis": "KEP",
        "nomor": "KEP-25/PJ/2016",
        "title": "Penetapan Nilai Bumi Berupa Permukaan Bumi untuk PBB Sektor Perhutanan",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-01-20",
        "tanggal_berlaku": "2016-01-20",
        "status": "berlaku",
        "topik": ["PBB", "nilai bumi", "perhutanan", "penetapan"],
        "sektor": ["perhutanan"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Penetapan nilai bumi berupa permukaan bumi sebagai dasar pengenaan PBB sektor perhutanan.",
    },
    {
        "file": "KEP - 93.PJ.2019 - NJOP Tambang.pdf",
        "slug": "kep/kep-93-2019",
        "jenis": "KEP",
        "nomor": "KEP-93/PJ/2019",
        "title": "Penetapan Nilai Bumi Berupa Permukaan Bumi untuk PBB Sektor Pertambangan",
        "tahun": 2019,
        "tanggal_diundangkan": "2019-03-22",
        "tanggal_berlaku": "2019-03-22",
        "status": "berlaku",
        "topik": ["PBB", "NJOP", "pertambangan", "nilai bumi", "penetapan"],
        "sektor": ["pertambangan_minerba"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Penetapan nilai bumi berupa permukaan bumi sebagai dasar pengenaan PBB sektor pertambangan.",
    },
    {
        "file": "KEP-126 PJ 2015 tg Penetapan Nilai Bumi dan Sektor Lainnya.pdf",
        "slug": "kep/kep-126-2015",
        "jenis": "KEP",
        "nomor": "KEP-126/PJ/2015",
        "title": "Penetapan Nilai Bumi untuk PBB Sektor Lainnya",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-06-08",
        "tanggal_berlaku": "2015-06-08",
        "status": "berlaku",
        "topik": ["PBB", "nilai bumi", "sektor lainnya", "penetapan"],
        "sektor": ["lainnya"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Penetapan nilai bumi berupa permukaan bumi sebagai dasar pengenaan PBB sektor lainnya.",
    },
    {
        "file": "KEP46PJ2021.pdf",
        "slug": "kep/kep-46-2021",
        "jenis": "KEP",
        "nomor": "KEP-46/PJ/2021",
        "title": "Penetapan Nilai Bumi Berupa Tubuh Bumi untuk PBB Sektor Pertambangan Mineral dan Batubara",
        "tahun": 2021,
        "tanggal_diundangkan": "2021-02-10",
        "tanggal_berlaku": "2021-02-10",
        "status": "berlaku",
        "topik": ["PBB", "tubuh bumi", "pertambangan", "minerba", "penetapan"],
        "sektor": ["pertambangan_minerba"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Penetapan nilai bumi berupa tubuh bumi sebagai dasar pengenaan PBB sektor pertambangan mineral dan batubara.",
    },
    {
        "file": "kep56_2025.pdf",
        "slug": "kep/kep-56-2025",
        "jenis": "KEP",
        "nomor": "KEP-56/PJ/2025",
        "title": "Penetapan Nilai Bumi Berupa Permukaan Bumi untuk PBB",
        "tahun": 2025,
        "tanggal_diundangkan": "2025-02-28",
        "tanggal_berlaku": "2025-02-28",
        "status": "berlaku",
        "topik": ["PBB", "nilai bumi", "penetapan", "permukaan bumi"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Penetapan nilai bumi berupa permukaan bumi sebagai dasar pengenaan PBB tahun 2025.",
    },
    {
        "file": "KMK_458_2021.pdf",
        "slug": "kmk/kmk-458-2021",
        "jenis": "KMK",
        "nomor": "KMK-458/KMK.03/2021",
        "title": "Penetapan Besarnya NJOPTKP PBB",
        "tahun": 2021,
        "tanggal_diundangkan": "2021-12-15",
        "tanggal_berlaku": "2022-01-01",
        "status": "berlaku",
        "topik": ["PBB", "NJOPTKP", "penetapan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Penetapan besarnya Nilai Jual Objek Pajak Tidak Kena Pajak (NJOPTKP) sebagai dasar penghitungan PBB.",
    },
    {
        "file": "PER - 02.PJ.2015 SPPT.pdf",
        "slug": "per/per-02-2015",
        "jenis": "PER",
        "nomor": "PER-02/PJ/2015",
        "title": "Tata Cara Penerbitan SPPT PBB",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-01-12",
        "tanggal_berlaku": "2015-01-12",
        "status": "berlaku",
        "topik": ["PBB", "SPPT", "penerbitan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara penerbitan Surat Pemberitahuan Pajak Terutang (SPPT) Pajak Bumi dan Bangunan.",
    },
    {
        "file": "PER - 08.PJ.2019 - Tata Cara Pemberian Penyesuaian dan Penghapusan Nomor Objek Pajak PBB.pdf",
        "slug": "per/per-08-2019",
        "jenis": "PER",
        "nomor": "PER-08/PJ/2019",
        "title": "Tata Cara Pemberian, Penyesuaian, dan Penghapusan Nomor Objek Pajak PBB",
        "tahun": 2019,
        "tanggal_diundangkan": "2019-02-20",
        "tanggal_berlaku": "2019-02-20",
        "status": "berlaku",
        "topik": ["PBB", "NOP", "nomor objek pajak", "pendaftaran"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pemberian, penyesuaian, dan penghapusan Nomor Objek Pajak (NOP) PBB.",
    },
    {
        "file": "PER - 10.PJ.2019 - Bentuk dan Isi Surat Pemberitahuan Pajak Terutang Nothit SKP SKPLB PBB.pdf",
        "slug": "per/per-10-2019",
        "jenis": "PER",
        "nomor": "PER-10/PJ/2019",
        "title": "Bentuk dan Isi SPPT, Nota Penghitungan, SKP, dan SKPLB PBB",
        "tahun": 2019,
        "tanggal_diundangkan": "2019-03-01",
        "tanggal_berlaku": "2019-03-01",
        "status": "berlaku",
        "topik": ["PBB", "SPPT", "SKP", "SKPLB", "bentuk", "isi"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur bentuk dan isi Surat Pemberitahuan Pajak Terutang, Nota Penghitungan, SKP, dan SKPLB PBB.",
    },
    {
        "file": "PER - 19.PJ.2019.pdf",
        "slug": "per/per-19-2019",
        "jenis": "PER",
        "nomor": "PER-19/PJ/2019",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Minyak dan Gas Bumi",
        "tahun": 2019,
        "tanggal_diundangkan": "2019-10-15",
        "tanggal_berlaku": "2020-01-01",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "migas", "pengenaan"],
        "sektor": ["pertambangan_migas"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan minyak dan gas bumi.",
    },
    {
        "file": "PER - 27.PJ.2014 tg Tata Cara Penetapan NJOP Sebagai Dasar Pengenaan PBB.pdf",
        "slug": "per/per-27-2014",
        "jenis": "PER",
        "nomor": "PER-27/PJ/2014",
        "title": "Tata Cara Penetapan NJOP Sebagai Dasar Pengenaan PBB",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-09-22",
        "tanggal_berlaku": "2014-09-22",
        "status": "berlaku",
        "topik": ["PBB", "NJOP", "penetapan", "dasar pengenaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara penetapan Nilai Jual Objek Pajak (NJOP) sebagai dasar pengenaan Pajak Bumi dan Bangunan.",
    },
    {
        "file": "PER - 29.PJ.2016 ttg Tata Cara Pemetaan Objek Pajak PBB.pdf",
        "slug": "per/per-29-2016",
        "jenis": "PER",
        "nomor": "PER-29/PJ/2016",
        "title": "Tata Cara Pemetaan Objek Pajak PBB",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-10-05",
        "tanggal_berlaku": "2016-10-05",
        "status": "berlaku",
        "topik": ["PBB", "pemetaan", "objek pajak"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pemetaan objek pajak Pajak Bumi dan Bangunan.",
    },
    {
        "file": "PER - 31.PJ.2014 Pengenaan Kebun_compressed.pdf",
        "slug": "per/per-31-2014",
        "jenis": "PER",
        "nomor": "PER-31/PJ/2014",
        "title": "Tata Cara Pengenaan PBB Sektor Perkebunan",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-11-14",
        "tanggal_berlaku": "2015-01-01",
        "status": "berlaku",
        "topik": ["PBB", "perkebunan", "pengenaan"],
        "sektor": ["perkebunan"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor perkebunan.",
    },
    {
        "file": "PER - 42.PJ.2015 - Tata Cara Pengenaan PBB Sektor Perhutanan_compressed.pdf",
        "slug": "per/per-42-2015",
        "jenis": "PER",
        "nomor": "PER-42/PJ/2015",
        "title": "Tata Cara Pengenaan PBB Sektor Perhutanan",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-11-23",
        "tanggal_berlaku": "2016-01-01",
        "status": "berlaku",
        "topik": ["PBB", "perhutanan", "pengenaan"],
        "sektor": ["perhutanan"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor perhutanan.",
    },
    {
        "file": "PER - 45.PJ.2013 tg Tata Cara Pengenaan PBB Sektor Pertambangan.pdf",
        "slug": "per/per-45-2013",
        "jenis": "PER",
        "nomor": "PER-45/PJ/2013",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Panas Bumi",
        "tahun": 2013,
        "tanggal_diundangkan": "2013-12-20",
        "tanggal_berlaku": "2014-01-01",
        "status": "dicabut",
        "topik": ["PBB", "pertambangan", "panas bumi", "pengenaan"],
        "sektor": ["panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "dicabut_oleh": "PMK-67/PMK.03/2020",
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan panas bumi (dicabut oleh PMK-67/2020).",
    },
    {
        "file": "PER -24.PJ.2016.pdf",
        "slug": "per/per-24-2016",
        "jenis": "PER",
        "nomor": "PER-24/PJ/2016",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Panas Bumi",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-08-31",
        "tanggal_berlaku": "2016-10-01",
        "status": "dicabut",
        "topik": ["PBB", "pertambangan", "panas bumi", "pengenaan"],
        "sektor": ["panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "dicabut_oleh": "PMK-67/PMK.03/2020",
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan panas bumi (dicabut oleh PMK-67/2020).",
    },
    {
        "file": "PER-20 PJ 2015 tg Tata Cara Pengenaan PBB Sektor Lainnya_compressed.pdf",
        "slug": "per/per-20-2015",
        "jenis": "PER",
        "nomor": "PER-20/PJ/2015",
        "title": "Tata Cara Pengenaan PBB Sektor Lainnya",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-06-08",
        "tanggal_berlaku": "2015-08-01",
        "status": "berlaku",
        "topik": ["PBB", "sektor lainnya", "pengenaan"],
        "sektor": ["lainnya"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor lainnya.",
    },
    {
        "file": "PER-23 PJ 2021 SPOP.pdf",
        "slug": "per/per-23-2021",
        "jenis": "PER",
        "nomor": "PER-23/PJ/2021",
        "title": "Bentuk, Isi, dan Tata Cara Pengisian SPOP PBB",
        "tahun": 2021,
        "tanggal_diundangkan": "2021-12-14",
        "tanggal_berlaku": "2022-01-01",
        "status": "berlaku",
        "topik": ["PBB", "SPOP", "bentuk", "isi", "pengisian"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur bentuk, isi, dan tata cara pengisian Surat Pemberitahuan Objek Pajak (SPOP) PBB.",
    },
    {
        "file": "PER-47 PJ 2015 tentang PBB Minerba.pdf",
        "slug": "per/per-47-2015",
        "jenis": "PER",
        "nomor": "PER-47/PJ/2015",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Mineral dan Batubara",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-12-22",
        "tanggal_berlaku": "2016-01-01",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "mineral", "batubara", "pengenaan"],
        "sektor": ["pertambangan_minerba"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan mineral dan batubara.",
    },
    {
        "file": "PER_25_PJ_2020 (1).pdf",
        "slug": "per/per-25-2020",
        "jenis": "PER",
        "nomor": "PER-25/PJ/2020",
        "title": "Tata Cara Pengenaan PBB Sektor Perikanan",
        "tahun": 2020,
        "tanggal_diundangkan": "2020-12-01",
        "tanggal_berlaku": "2021-01-01",
        "status": "berlaku",
        "topik": ["PBB", "perikanan", "pengenaan"],
        "sektor": ["perikanan"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor perikanan.",
    },
    {
        "file": "Perubahan2_KEP59PJ2023.pdf",
        "slug": "kep/kep-59-2023-perubahan2",
        "jenis": "KEP",
        "nomor": "Perubahan Kedua KEP-59/PJ/2023",
        "title": "Perubahan Kedua atas KEP-59/PJ/2023 tentang Penetapan Nilai Bumi",
        "tahun": 2023,
        "tanggal_diundangkan": "2023-12-01",
        "tanggal_berlaku": "2023-12-01",
        "status": "berlaku",
        "topik": ["PBB", "nilai bumi", "penetapan", "perubahan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "mengubah": "KEP-59/PJ/2023",
        "ringkasan": "Perubahan kedua atas KEP-59/PJ/2023 tentang penetapan nilai bumi untuk PBB.",
    },
    {
        "file": "PMK - 17.PMK03.2011 tg Permohonan Pengembalian Kelebihan Pembayaran PBB.pdf",
        "slug": "pmk/pmk-17-2011",
        "jenis": "PMK",
        "nomor": "PMK-17/PMK.03/2011",
        "title": "Permohonan Pengembalian Kelebihan Pembayaran PBB",
        "tahun": 2011,
        "tanggal_diundangkan": "2011-01-24",
        "tanggal_berlaku": "2011-02-24",
        "status": "berlaku",
        "topik": ["PBB", "restitusi", "pengembalian", "kelebihan pembayaran"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara permohonan pengembalian kelebihan pembayaran Pajak Bumi dan Bangunan.",
    },
    {
        "file": "PMK - 242_2014_Pembayaran_compressed.pdf",
        "slug": "pmk/pmk-242-2014",
        "jenis": "PMK",
        "nomor": "PMK-242/PMK.03/2014",
        "title": "Tata Cara Pembayaran dan Penyetoran Pajak",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-12-24",
        "tanggal_berlaku": "2015-01-01",
        "status": "berlaku",
        "topik": ["pembayaran", "penyetoran", "pajak"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB", "PPh", "PPN"],
        "ringkasan": "Mengatur tata cara pembayaran dan penyetoran pajak termasuk PBB.",
    },
    {
        "file": "PMK - 244.PMK03.2015 tg Tata Cara Penghitungan dan Pengembalian Kelebihan Pembayaran Pajak_compressed.pdf",
        "slug": "pmk/pmk-244-2015",
        "jenis": "PMK",
        "nomor": "PMK-244/PMK.03/2015",
        "title": "Tata Cara Penghitungan dan Pengembalian Kelebihan Pembayaran Pajak",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-12-21",
        "tanggal_berlaku": "2016-01-01",
        "status": "berlaku",
        "topik": ["restitusi", "pengembalian", "kelebihan pembayaran"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB", "PPh", "PPN"],
        "ringkasan": "Mengatur tata cara penghitungan dan pengembalian kelebihan pembayaran pajak.",
    },
    {
        "file": "PMK - 253~PMK.03~2014Per.pdf",
        "slug": "pmk/pmk-253-2014",
        "jenis": "PMK",
        "nomor": "PMK-253/PMK.03/2014",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Panas Bumi",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-12-19",
        "tanggal_berlaku": "2015-01-01",
        "status": "dicabut",
        "topik": ["PBB", "pertambangan", "panas bumi", "pengenaan"],
        "sektor": ["panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "dicabut_oleh": "PMK-67/PMK.03/2020",
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan panas bumi (dicabut oleh PMK-67/2020).",
    },
    {
        "file": "PMK - 254~PMK.03~2014Per.pdf",
        "slug": "pmk/pmk-254-2014",
        "jenis": "PMK",
        "nomor": "PMK-254/PMK.03/2014",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Minyak Bumi dan Gas Bumi",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-12-19",
        "tanggal_berlaku": "2015-01-01",
        "status": "dicabut",
        "topik": ["PBB", "pertambangan", "migas", "pengenaan"],
        "sektor": ["pertambangan_migas"],
        "berlaku_untuk": ["PBB"],
        "dicabut_oleh": "PMK-122/PMK.03/2019",
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan minyak bumi dan gas bumi (dicabut oleh PMK-122/2019).",
    },
    {
        "file": "PMK - 255~PMK.03~2014Per.pdf",
        "slug": "pmk/pmk-255-2014",
        "jenis": "PMK",
        "nomor": "PMK-255/PMK.03/2014",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Mineral dan Batubara",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-12-19",
        "tanggal_berlaku": "2015-01-01",
        "status": "dicabut",
        "topik": ["PBB", "pertambangan", "minerba", "pengenaan"],
        "sektor": ["pertambangan_minerba"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan mineral dan batubara (dicabut).",
    },
    {
        "file": "PMK - 256~PMK.03~2014 ttg Tata Cara Pemeriksaan dan Penelitian PBB.pdf",
        "slug": "pmk/pmk-256-2014",
        "jenis": "PMK",
        "nomor": "PMK-256/PMK.03/2014",
        "title": "Tata Cara Pemeriksaan dan Penelitian PBB",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-12-19",
        "tanggal_berlaku": "2015-01-01",
        "status": "berlaku",
        "topik": ["PBB", "pemeriksaan", "penelitian"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pemeriksaan dan penelitian Pajak Bumi dan Bangunan.",
    },
    {
        "file": "PMK - 26.PMK03.2015 Perubahan PMK - 76 PBB Migas.pdf",
        "slug": "pmk/pmk-26-2015",
        "jenis": "PMK",
        "nomor": "PMK-26/PMK.03/2015",
        "title": "Perubahan atas PMK-76/PMK.03/2013 tentang Penatausahaan PBB Sektor Pertambangan Migas dan Panas Bumi",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-02-12",
        "tanggal_berlaku": "2015-03-14",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "migas", "panas bumi", "penatausahaan", "perubahan"],
        "sektor": ["pertambangan_migas", "panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "mengubah": "PMK-76/PMK.03/2013",
        "ringkasan": "Perubahan atas PMK-76/PMK.03/2013 tentang penatausahaan PBB sektor pertambangan migas dan panas bumi.",
    },
    {
        "file": "PMK - 267~PMK.011~2014Per.pdf",
        "slug": "pmk/pmk-267-2014",
        "jenis": "PMK",
        "nomor": "PMK-267/PMK.011/2014",
        "title": "Pengurangan PBB Sektor Pertambangan Panas Bumi",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-12-29",
        "tanggal_berlaku": "2015-01-01",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "panas bumi", "pengurangan", "fasilitas"],
        "sektor": ["panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur pengurangan PBB sektor pertambangan panas bumi.",
    },
    {
        "file": "PMK - 76.PMK03.2013 tg Penatausahaan PBB Sektor Pertambangan untuk Migas dan Panas Bumi.pdf",
        "slug": "pmk/pmk-76-2013",
        "jenis": "PMK",
        "nomor": "PMK-76/PMK.03/2013",
        "title": "Penatausahaan PBB Sektor Pertambangan untuk Pertambangan Minyak Bumi, Gas Bumi, dan Panas Bumi",
        "tahun": 2013,
        "tanggal_diundangkan": "2013-04-10",
        "tanggal_berlaku": "2013-05-10",
        "status": "diubah",
        "topik": ["PBB", "pertambangan", "migas", "panas bumi", "penatausahaan"],
        "sektor": ["pertambangan_migas", "panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "diubah_oleh": ["PMK-26/PMK.03/2015"],
        "ringkasan": "Mengatur penatausahaan PBB sektor pertambangan untuk migas dan panas bumi.",
    },
    {
        "file": "PMK 11 2013 tentang tata cara pembetulan.rebuild.pdf",
        "slug": "pmk/pmk-11-2013",
        "jenis": "PMK",
        "nomor": "PMK-11/PMK.03/2013",
        "title": "Tata Cara Pembetulan",
        "tahun": 2013,
        "tanggal_diundangkan": "2013-01-07",
        "tanggal_berlaku": "2013-02-06",
        "status": "berlaku",
        "topik": ["pembetulan", "PBB"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pembetulan terkait PBB.",
    },
    {
        "file": "PMK 131_PMK.03_2017.pdf",
        "slug": "pmk/pmk-131-2017",
        "jenis": "PMK",
        "nomor": "PMK-131/PMK.03/2017",
        "title": "Perubahan Kedua atas PMK-76/PMK.03/2013 tentang Penatausahaan PBB Sektor Pertambangan",
        "tahun": 2017,
        "tanggal_diundangkan": "2017-09-25",
        "tanggal_berlaku": "2017-10-25",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "migas", "panas bumi", "penatausahaan", "perubahan"],
        "sektor": ["pertambangan_migas", "panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "mengubah": "PMK-76/PMK.03/2013",
        "ringkasan": "Perubahan kedua atas PMK-76/PMK.03/2013 tentang penatausahaan PBB sektor pertambangan migas dan panas bumi.",
    },
    {
        "file": "PMK 172 2016 Pengurangang Pabum.pdf",
        "slug": "pmk/pmk-172-2016",
        "jenis": "PMK",
        "nomor": "PMK-172/PMK.03/2016",
        "title": "Perubahan atas PMK-267/PMK.011/2014 tentang Pengurangan PBB Sektor Pertambangan Panas Bumi",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-11-11",
        "tanggal_berlaku": "2016-12-11",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "panas bumi", "pengurangan", "fasilitas", "perubahan"],
        "sektor": ["panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "mengubah": "PMK-267/PMK.011/2014",
        "ringkasan": "Perubahan atas PMK-267/PMK.011/2014 tentang pengurangan PBB sektor pertambangan panas bumi.",
    },
    {
        "file": "PMK 186 PMK.03_2019Per.pdf",
        "slug": "pmk/pmk-186-2019",
        "jenis": "PMK",
        "nomor": "PMK-186/PMK.03/2019",
        "title": "Klasifikasi Objek Pajak dan Tata Cara Penetapan NJOP PBB",
        "tahun": 2019,
        "tanggal_diundangkan": "2019-12-12",
        "tanggal_berlaku": "2020-01-01",
        "status": "diubah",
        "topik": ["klasifikasi", "NJOP", "PBB", "penetapan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "diubah_oleh": ["PMK-234/PMK.03/2022"],
        "ringkasan": "Mengatur klasifikasi objek pajak dan tata cara penetapan NJOP PBB.",
    },
    {
        "file": "PMK 249 PMK 03 2016 Keberatan.pdf",
        "slug": "pmk/pmk-249-2016",
        "jenis": "PMK",
        "nomor": "PMK-249/PMK.03/2016",
        "title": "Tata Cara Penyelesaian Keberatan PBB",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-12-30",
        "tanggal_berlaku": "2017-02-01",
        "status": "berlaku",
        "topik": ["PBB", "keberatan", "penyelesaian"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara penyelesaian keberatan Pajak Bumi dan Bangunan.",
    },
    {
        "file": "PMK.23.PMK.03.2014_Penyesuaian_NJOPTKP.pdf",
        "slug": "pmk/pmk-23-2014",
        "jenis": "PMK",
        "nomor": "PMK-23/PMK.03/2014",
        "title": "Penyesuaian Besarnya NJOPTKP PBB",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-01-31",
        "tanggal_berlaku": "2014-03-02",
        "status": "berlaku",
        "topik": ["PBB", "NJOPTKP", "penyesuaian"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur penyesuaian besarnya Nilai Jual Objek Pajak Tidak Kena Pajak (NJOPTKP) PBB.",
    },
    {
        "file": "PMK_129_2023.pdf",
        "slug": "pmk/pmk-129-2023",
        "jenis": "PMK",
        "nomor": "PMK-129/PMK.03/2023",
        "title": "Tata Cara Pengenaan PBB Sektor Pertambangan Mineral dan Batubara",
        "tahun": 2023,
        "tanggal_diundangkan": "2023-11-30",
        "tanggal_berlaku": "2024-01-01",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "mineral", "batubara", "pengenaan"],
        "sektor": ["pertambangan_minerba"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur tata cara pengenaan PBB sektor pertambangan mineral dan batubara (menggantikan regulasi sebelumnya).",
    },
    {
        "file": "PMK_139_2014.pdf",
        "slug": "pmk/pmk-139-2014",
        "jenis": "PMK",
        "nomor": "PMK-139/PMK.03/2014",
        "title": "Klasifikasi dan Penetapan NJOP sebagai Dasar Pengenaan PBB",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-07-21",
        "tanggal_berlaku": "2014-08-20",
        "status": "dicabut",
        "topik": ["klasifikasi", "NJOP", "PBB", "penetapan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "dicabut_oleh": "PMK-186/PMK.03/2019",
        "ringkasan": "Mengatur klasifikasi dan penetapan NJOP sebagai dasar pengenaan PBB (dicabut oleh PMK-186/2019).",
    },
    {
        "file": "PMK_234_2022.pdf",
        "slug": "pmk/pmk-234-2022",
        "jenis": "PMK",
        "nomor": "PMK-234/PMK.03/2022",
        "title": "Perubahan atas PMK-186/PMK.03/2019 tentang Klasifikasi Objek Pajak dan Tata Cara Penetapan NJOP PBB",
        "tahun": 2022,
        "tanggal_diundangkan": "2022-12-30",
        "tanggal_berlaku": "2023-01-01",
        "status": "berlaku",
        "topik": ["klasifikasi", "NJOP", "PBB", "penetapan", "perubahan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "mengubah": "PMK-186/PMK.03/2019",
        "ringkasan": "Perubahan atas PMK-186/PMK.03/2019 tentang klasifikasi objek pajak dan tata cara penetapan NJOP PBB.",
    },
    {
        "file": "PMK_79_2023.pdf",
        "slug": "pmk/pmk-79-2023",
        "jenis": "PMK",
        "nomor": "PMK-79/PMK.03/2023",
        "title": "Tata Cara Penilaian untuk Tujuan Perpajakan",
        "tahun": 2023,
        "tanggal_diundangkan": "2023-08-24",
        "tanggal_berlaku": "2023-09-23",
        "status": "berlaku",
        "topik": ["penilaian", "perpajakan", "harta berwujud", "harta tidak berwujud", "bisnis"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PPh", "PPN", "PBB", "PPSP"],
        "ringkasan": "Mengatur tata cara penilaian untuk keperluan perpajakan meliputi penilaian harta berwujud, tidak berwujud, dan bisnis.",
    },
    {
        "file": "PMK_80_2023.pdf",
        "slug": "pmk/pmk-80-2023",
        "jenis": "PMK",
        "nomor": "PMK-80/PMK.03/2023",
        "title": "Tata Cara Penerbitan Surat Ketetapan Pajak dan Surat Tagihan Pajak",
        "tahun": 2023,
        "tanggal_diundangkan": "2023-08-24",
        "tanggal_berlaku": "2023-09-23",
        "status": "berlaku",
        "topik": ["SKP", "STP", "penerbitan", "ketetapan pajak"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB", "PPh", "PPN"],
        "ringkasan": "Mengatur tata cara penerbitan Surat Ketetapan Pajak dan Surat Tagihan Pajak.",
    },
    {
        "file": "PP 25 2002.pdf",
        "slug": "pp/pp-25-2002",
        "jenis": "PP",
        "nomor": "PP-25/2002",
        "title": "Penetapan Besarnya NJKP untuk Penghitungan PBB",
        "tahun": 2002,
        "tanggal_diundangkan": "2002-05-13",
        "tanggal_berlaku": "2002-05-13",
        "status": "berlaku",
        "topik": ["PBB", "NJKP", "penetapan", "penghitungan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Penetapan besarnya Nilai Jual Kena Pajak (NJKP) sebagai dasar penghitungan PBB.",
    },
    {
        "file": "PP No.16 TH 2000.pdf",
        "slug": "pp/pp-16-2000",
        "jenis": "PP",
        "nomor": "PP-16/2000",
        "title": "Pembagian Hasil Penerimaan PBB antara Pemerintah Pusat dan Daerah",
        "tahun": 2000,
        "tanggal_diundangkan": "2000-06-20",
        "tanggal_berlaku": "2000-06-20",
        "status": "berlaku",
        "topik": ["PBB", "pembagian", "penerimaan", "pusat", "daerah"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur pembagian hasil penerimaan PBB antara Pemerintah Pusat dan Pemerintah Daerah.",
    },
    {
        "file": "pp_79_2010_Cost Recovery.pdf",
        "slug": "pp/pp-79-2010",
        "jenis": "PP",
        "nomor": "PP-79/2010",
        "title": "Biaya Operasi yang Dapat Dikembalikan dan Perlakuan PPh di Bidang Usaha Hulu Minyak dan Gas Bumi",
        "tahun": 2010,
        "tanggal_diundangkan": "2010-12-20",
        "tanggal_berlaku": "2010-12-20",
        "status": "berlaku",
        "topik": ["cost recovery", "migas", "hulu", "PPh", "biaya operasi"],
        "sektor": ["pertambangan_migas"],
        "berlaku_untuk": ["PPh"],
        "ringkasan": "Mengatur biaya operasi yang dapat dikembalikan (cost recovery) dan perlakuan PPh di bidang usaha hulu migas.",
    },
    {
        "file": "Salinan KEP-185.PJ.2020.pdf",
        "slug": "kep/kep-185-2020",
        "jenis": "KEP",
        "nomor": "KEP-185/PJ/2020",
        "title": "Penetapan Nilai Bumi Berupa Permukaan Bumi untuk PBB",
        "tahun": 2020,
        "tanggal_diundangkan": "2020-04-01",
        "tanggal_berlaku": "2020-04-01",
        "status": "berlaku",
        "topik": ["PBB", "nilai bumi", "penetapan", "permukaan bumi"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Penetapan nilai bumi berupa permukaan bumi sebagai dasar pengenaan PBB tahun 2020.",
    },
    {
        "file": "Salinan_KEP_59_PJ_2023.pdf",
        "slug": "kep/kep-59-2023",
        "jenis": "KEP",
        "nomor": "KEP-59/PJ/2023",
        "title": "Penetapan Nilai Bumi Berupa Permukaan Bumi untuk PBB",
        "tahun": 2023,
        "tanggal_diundangkan": "2023-03-31",
        "tanggal_berlaku": "2023-03-31",
        "status": "diubah",
        "topik": ["PBB", "nilai bumi", "penetapan", "permukaan bumi"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "diubah_oleh": ["Perubahan Kedua KEP-59/PJ/2023"],
        "ringkasan": "Penetapan nilai bumi berupa permukaan bumi sebagai dasar pengenaan PBB tahun 2023.",
    },
    {
        "file": "scan SE_02_2022_OCR.pdf",
        "slug": "se/se-02-2022",
        "jenis": "SE",
        "nomor": "SE-02/PJ/2022",
        "title": "Petunjuk Pelaksanaan Pemetaan Objek Pajak PBB",
        "tahun": 2022,
        "tanggal_diundangkan": "2022-02-01",
        "tanggal_berlaku": "2022-02-01",
        "status": "berlaku",
        "topik": ["PBB", "pemetaan", "objek pajak", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pemetaan objek pajak PBB.",
    },
    {
        "file": "SDSN-UU-PBB.pdf",
        "slug": "uu/uu-12-1985",
        "jenis": "UU",
        "nomor": "UU-12/1985 jo. UU-12/1994",
        "title": "Undang-Undang Pajak Bumi dan Bangunan",
        "tahun": 1985,
        "tanggal_diundangkan": "1985-12-27",
        "tanggal_berlaku": "1986-01-01",
        "status": "berlaku",
        "topik": ["PBB", "undang-undang", "dasar hukum"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Undang-Undang Pajak Bumi dan Bangunan sebagaimana telah diubah dengan UU Nomor 12 Tahun 1994.",
    },
    {
        "file": "SE - 05.PJ.2016 ttg Kehutanan.pdf",
        "slug": "se/se-05-2016",
        "jenis": "SE",
        "nomor": "SE-05/PJ/2016",
        "title": "Petunjuk Pelaksanaan Pengenaan PBB Sektor Kehutanan",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-02-24",
        "tanggal_berlaku": "2016-02-24",
        "status": "berlaku",
        "topik": ["PBB", "kehutanan", "perhutanan", "petunjuk pelaksanaan"],
        "sektor": ["perhutanan"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pengenaan PBB sektor kehutanan.",
    },
    {
        "file": "SE - 23.PJ.2011 tg Juklak PMK-17.2011 tg Permohonan Restitusi PBB.pdf",
        "slug": "se/se-23-2011",
        "jenis": "SE",
        "nomor": "SE-23/PJ/2011",
        "title": "Petunjuk Pelaksanaan PMK-17/2011 tentang Permohonan Restitusi PBB",
        "tahun": 2011,
        "tanggal_diundangkan": "2011-08-09",
        "tanggal_berlaku": "2011-08-09",
        "status": "berlaku",
        "topik": ["PBB", "restitusi", "pengembalian", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "dasar_hukum": "PMK-17/PMK.03/2011",
        "ringkasan": "Petunjuk pelaksanaan PMK-17/PMK.03/2011 tentang permohonan pengembalian kelebihan pembayaran PBB.",
    },
    {
        "file": "SE - 33.PJ.2019.pdf",
        "slug": "se/se-33-2019",
        "jenis": "SE",
        "nomor": "SE-33/PJ/2019",
        "title": "Petunjuk Pelaksanaan Pengenaan PBB Sektor Pertambangan Minyak dan Gas Bumi",
        "tahun": 2019,
        "tanggal_diundangkan": "2019-12-23",
        "tanggal_berlaku": "2020-01-01",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "migas", "petunjuk pelaksanaan"],
        "sektor": ["pertambangan_migas"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pengenaan PBB sektor pertambangan minyak dan gas bumi.",
    },
    {
        "file": "SE - 36.PJ.2014 tg Petunjuk Pelaksanaan PER-27 PJ 2014.pdf",
        "slug": "se/se-36-2014",
        "jenis": "SE",
        "nomor": "SE-36/PJ/2014",
        "title": "Petunjuk Pelaksanaan PER-27/PJ/2014 tentang Penetapan NJOP",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-11-21",
        "tanggal_berlaku": "2014-11-21",
        "status": "berlaku",
        "topik": ["PBB", "NJOP", "penetapan", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "dasar_hukum": "PER-27/PJ/2014",
        "ringkasan": "Petunjuk pelaksanaan PER-27/PJ/2014 tentang tata cara penetapan NJOP sebagai dasar pengenaan PBB.",
    },
    {
        "file": "SE - 37.PJ.2017 tg Petunjuk Pelaksanaan Penyelesaian Keberatan Pajak Bumi dan Bangunan.pdf",
        "slug": "se/se-37-2017",
        "jenis": "SE",
        "nomor": "SE-37/PJ/2017",
        "title": "Petunjuk Pelaksanaan Penyelesaian Keberatan PBB",
        "tahun": 2017,
        "tanggal_diundangkan": "2017-12-12",
        "tanggal_berlaku": "2017-12-12",
        "status": "berlaku",
        "topik": ["PBB", "keberatan", "penyelesaian", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan penyelesaian keberatan Pajak Bumi dan Bangunan.",
    },
    {
        "file": "SE - 42.PJ.2014 - Juklak Pengenaan PBB Perkebunan_compressed.pdf",
        "slug": "se/se-42-2014",
        "jenis": "SE",
        "nomor": "SE-42/PJ/2014",
        "title": "Petunjuk Pelaksanaan Pengenaan PBB Sektor Perkebunan",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-12-15",
        "tanggal_berlaku": "2015-01-01",
        "status": "berlaku",
        "topik": ["PBB", "perkebunan", "petunjuk pelaksanaan"],
        "sektor": ["perkebunan"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pengenaan PBB sektor perkebunan.",
    },
    {
        "file": "SE - 43.PJ.2017 tg Petunjuk Pelaksanaan Pengurangan Denda Administrasi PBB dan Pengurangan Atau Pembatalan SPPT, SKP PBB, STP PBB Yang Tidak Benar.pdf",
        "slug": "se/se-43-2017",
        "jenis": "SE",
        "nomor": "SE-43/PJ/2017",
        "title": "Petunjuk Pelaksanaan Pengurangan Denda Administrasi PBB dan Pengurangan atau Pembatalan SPPT, SKP PBB, STP PBB yang Tidak Benar",
        "tahun": 2017,
        "tanggal_diundangkan": "2017-12-13",
        "tanggal_berlaku": "2017-12-13",
        "status": "berlaku",
        "topik": ["PBB", "pengurangan", "denda", "pembatalan", "SPPT", "SKP", "STP", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "dasar_hukum": "PMK-81/PMK.03/2017",
        "ringkasan": "Petunjuk pelaksanaan pengurangan denda administrasi PBB dan pengurangan/pembatalan SPPT, SKP PBB, STP PBB yang tidak benar.",
    },
    {
        "file": "SE - 44.PJ.2017 tg Petunjuk Pelaksanaan Pemberian Pengurangan Pajak Bumi dan Bangunan.pdf",
        "slug": "se/se-44-2017",
        "jenis": "SE",
        "nomor": "SE-44/PJ/2017",
        "title": "Petunjuk Pelaksanaan Pemberian Pengurangan PBB",
        "tahun": 2017,
        "tanggal_diundangkan": "2017-12-13",
        "tanggal_berlaku": "2017-12-13",
        "status": "berlaku",
        "topik": ["PBB", "pengurangan", "fasilitas", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "dasar_hukum": "PMK-82/PMK.03/2017",
        "ringkasan": "Petunjuk pelaksanaan pemberian pengurangan Pajak Bumi dan Bangunan.",
    },
    {
        "file": "SE - 48.PJ.2015 Geotagging.pdf",
        "slug": "se/se-48-2015",
        "jenis": "SE",
        "nomor": "SE-48/PJ/2015",
        "title": "Petunjuk Pelaksanaan Geotagging dalam rangka Pendataan Objek Pajak PBB",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-12-23",
        "tanggal_berlaku": "2015-12-23",
        "status": "berlaku",
        "topik": ["PBB", "geotagging", "pendataan", "objek pajak"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan geotagging dalam rangka pendataan objek pajak PBB.",
    },
    {
        "file": "SE 15_PJ_2018 tentang Kebijakan Pemeriksaan.pdf",
        "slug": "se/se-15-2018",
        "jenis": "SE",
        "nomor": "SE-15/PJ/2018",
        "title": "Kebijakan Pemeriksaan PBB",
        "tahun": 2018,
        "tanggal_diundangkan": "2018-05-23",
        "tanggal_berlaku": "2018-05-23",
        "status": "berlaku",
        "topik": ["PBB", "pemeriksaan", "kebijakan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur kebijakan pemeriksaan Pajak Bumi dan Bangunan.",
    },
    {
        "file": "SE 45 th 2015 tentang Juklak Pendaftaran dan Pemutakhiran PBB_compressed.pdf",
        "slug": "se/se-45-2015",
        "jenis": "SE",
        "nomor": "SE-45/PJ/2015",
        "title": "Petunjuk Pelaksanaan Pendaftaran dan Pemutakhiran PBB",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-12-16",
        "tanggal_berlaku": "2015-12-16",
        "status": "berlaku",
        "topik": ["PBB", "pendaftaran", "pemutakhiran", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pendaftaran dan pemutakhiran objek pajak PBB.",
    },
    {
        "file": "SE-04_PJ_2021 (2).pdf",
        "slug": "se/se-04-2021",
        "jenis": "SE",
        "nomor": "SE-04/PJ/2021",
        "title": "Petunjuk Pelaksanaan Pengenaan PBB Sektor Pertambangan Panas Bumi",
        "tahun": 2021,
        "tanggal_diundangkan": "2021-02-10",
        "tanggal_berlaku": "2021-02-10",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "panas bumi", "petunjuk pelaksanaan"],
        "sektor": ["panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pengenaan PBB sektor pertambangan panas bumi.",
    },
    {
        "file": "SE-11-2022.pdf",
        "slug": "se/se-11-2022",
        "jenis": "SE",
        "nomor": "SE-11/PJ/2022",
        "title": "Petunjuk Pelaksanaan Penilaian PBB Sektor Pertambangan Mineral dan Batubara",
        "tahun": 2022,
        "tanggal_diundangkan": "2022-04-08",
        "tanggal_berlaku": "2022-04-08",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "mineral", "batubara", "penilaian", "petunjuk pelaksanaan"],
        "sektor": ["pertambangan_minerba"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan penilaian PBB sektor pertambangan mineral dan batubara.",
    },
    {
        "file": "SE-11PJ2022 Penilaian NJOP PBB.pdf",
        "slug": "se/se-11-2022-njop",
        "jenis": "SE",
        "nomor": "SE-11/PJ/2022 (Lampiran Penilaian NJOP)",
        "title": "Lampiran Penilaian NJOP PBB - SE-11/PJ/2022",
        "tahun": 2022,
        "tanggal_diundangkan": "2022-04-08",
        "tanggal_berlaku": "2022-04-08",
        "status": "berlaku",
        "topik": ["PBB", "NJOP", "penilaian", "lampiran"],
        "sektor": ["pertambangan_minerba"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Lampiran penilaian NJOP PBB terkait SE-11/PJ/2022.",
    },
    {
        "file": "SE-16_PJ_2025_Pedoman_Pelaksanaan_Pemberian_Pengurangan_PBB.pdf",
        "slug": "se/se-16-2025",
        "jenis": "SE",
        "nomor": "SE-16/PJ/2025",
        "title": "Pedoman Pelaksanaan Pemberian Pengurangan PBB",
        "tahun": 2025,
        "tanggal_diundangkan": "2025-03-10",
        "tanggal_berlaku": "2025-03-10",
        "status": "berlaku",
        "topik": ["PBB", "pengurangan", "pedoman", "fasilitas"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Pedoman pelaksanaan pemberian pengurangan Pajak Bumi dan Bangunan.",
    },
    {
        "file": "SE-17.PJ.2020 - Petunjuk Pelaksanaan PMK.186.2019 bookmarked.pdf",
        "slug": "se/se-17-2020",
        "jenis": "SE",
        "nomor": "SE-17/PJ/2020",
        "title": "Petunjuk Pelaksanaan PMK-186/2019 tentang Klasifikasi dan Penetapan NJOP PBB",
        "tahun": 2020,
        "tanggal_diundangkan": "2020-03-17",
        "tanggal_berlaku": "2020-03-17",
        "status": "berlaku",
        "topik": ["PBB", "klasifikasi", "NJOP", "penetapan", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "dasar_hukum": "PMK-186/PMK.03/2019",
        "ringkasan": "Petunjuk pelaksanaan PMK-186/PMK.03/2019 tentang klasifikasi objek pajak dan tata cara penetapan NJOP PBB.",
    },
    {
        "file": "SE-25 PJ 2015 Kebijakan Pemeriksaan dan Penelitian PBB_compressed_opt.pdf",
        "slug": "se/se-25-2015",
        "jenis": "SE",
        "nomor": "SE-25/PJ/2015",
        "title": "Kebijakan Pemeriksaan dan Penelitian PBB",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-05-18",
        "tanggal_berlaku": "2015-05-18",
        "status": "berlaku",
        "topik": ["PBB", "pemeriksaan", "penelitian", "kebijakan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Mengatur kebijakan pemeriksaan dan penelitian PBB.",
    },
    {
        "file": "SE-25.PJ.2020_pembayaran_pbb_migas_bookmarked.pdf",
        "slug": "se/se-25-2020",
        "jenis": "SE",
        "nomor": "SE-25/PJ/2020",
        "title": "Petunjuk Pelaksanaan Pembayaran PBB Sektor Pertambangan Migas",
        "tahun": 2020,
        "tanggal_diundangkan": "2020-06-19",
        "tanggal_berlaku": "2020-06-19",
        "status": "berlaku",
        "topik": ["PBB", "pembayaran", "pertambangan", "migas", "petunjuk pelaksanaan"],
        "sektor": ["pertambangan_migas"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pembayaran PBB sektor pertambangan minyak dan gas bumi.",
    },
    {
        "file": "SE-33 PJ 2015 tg Petunjuk Pelaksanaan PER-20.PJ.2015 tg Tata Cara Pengenaan PBB Sektor Lainnya.pdf",
        "slug": "se/se-33-2015",
        "jenis": "SE",
        "nomor": "SE-33/PJ/2015",
        "title": "Petunjuk Pelaksanaan PER-20/PJ/2015 tentang Pengenaan PBB Sektor Lainnya",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-08-14",
        "tanggal_berlaku": "2015-08-14",
        "status": "berlaku",
        "topik": ["PBB", "sektor lainnya", "petunjuk pelaksanaan"],
        "sektor": ["lainnya"],
        "berlaku_untuk": ["PBB"],
        "dasar_hukum": "PER-20/PJ/2015",
        "ringkasan": "Petunjuk pelaksanaan PER-20/PJ/2015 tentang tata cara pengenaan PBB sektor lainnya.",
    },
    {
        "file": "SE-41_PJ_2015 Ttg Juklak Pembetulan_compressed.pdf",
        "slug": "se/se-41-2015",
        "jenis": "SE",
        "nomor": "SE-41/PJ/2015",
        "title": "Petunjuk Pelaksanaan Pembetulan PBB",
        "tahun": 2015,
        "tanggal_diundangkan": "2015-11-03",
        "tanggal_berlaku": "2015-11-03",
        "status": "berlaku",
        "topik": ["PBB", "pembetulan", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pembetulan terkait PBB.",
    },
    {
        "file": "SE-51 ttg Juklak Penerbitan STP PBB.pdf",
        "slug": "se/se-51-2016",
        "jenis": "SE",
        "nomor": "SE-51/PJ/2016",
        "title": "Petunjuk Pelaksanaan Penerbitan STP PBB",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-11-28",
        "tanggal_berlaku": "2016-11-28",
        "status": "berlaku",
        "topik": ["PBB", "STP", "surat tagihan", "penerbitan", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "dasar_hukum": "PMK-78/PMK.03/2016",
        "ringkasan": "Petunjuk pelaksanaan penerbitan Surat Tagihan Pajak (STP) PBB.",
    },
    {
        "file": "SE-64.PJ.2013_compressed.pdf",
        "slug": "se/se-64-2013",
        "jenis": "SE",
        "nomor": "SE-64/PJ/2013",
        "title": "Petunjuk Pelaksanaan Pengenaan PBB Sektor Pertambangan Panas Bumi",
        "tahun": 2013,
        "tanggal_diundangkan": "2013-12-30",
        "tanggal_berlaku": "2014-01-01",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "panas bumi", "petunjuk pelaksanaan"],
        "sektor": ["panas_bumi"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pengenaan PBB sektor pertambangan panas bumi.",
    },
    {
        "file": "SE_02_PJ_2021_Pemetaan_Kebun.pdf",
        "slug": "se/se-02-2021",
        "jenis": "SE",
        "nomor": "SE-02/PJ/2021",
        "title": "Petunjuk Pelaksanaan Pemetaan Objek Pajak PBB Sektor Perkebunan",
        "tahun": 2021,
        "tanggal_diundangkan": "2021-01-22",
        "tanggal_berlaku": "2021-01-22",
        "status": "berlaku",
        "topik": ["PBB", "pemetaan", "perkebunan", "petunjuk pelaksanaan"],
        "sektor": ["perkebunan"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pemetaan objek pajak PBB sektor perkebunan.",
    },
    {
        "file": "SE_16_PJ_2022_Pemetaan_Hutan.pdf",
        "slug": "se/se-16-2022",
        "jenis": "SE",
        "nomor": "SE-16/PJ/2022",
        "title": "Petunjuk Pelaksanaan Pemetaan Objek Pajak PBB Sektor Perhutanan",
        "tahun": 2022,
        "tanggal_diundangkan": "2022-05-20",
        "tanggal_berlaku": "2022-05-20",
        "status": "berlaku",
        "topik": ["PBB", "pemetaan", "perhutanan", "petunjuk pelaksanaan"],
        "sektor": ["perhutanan"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pemetaan objek pajak PBB sektor perhutanan.",
    },
    {
        "file": "SE_41_2014_Pelaksanaan Putusan Banding, Gugatan dan Peninjauan Kembali_2Sg9.pdf",
        "slug": "se/se-41-2014",
        "jenis": "SE",
        "nomor": "SE-41/PJ/2014",
        "title": "Petunjuk Pelaksanaan Putusan Banding, Gugatan, dan Peninjauan Kembali PBB",
        "tahun": 2014,
        "tanggal_diundangkan": "2014-10-24",
        "tanggal_berlaku": "2014-10-24",
        "status": "berlaku",
        "topik": ["PBB", "banding", "gugatan", "peninjauan kembali", "petunjuk pelaksanaan"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan putusan banding, gugatan, dan peninjauan kembali terkait PBB.",
    },
    {
        "file": "SE_53_PJ_2016 SE MINERBA_20161125103649441.pdf",
        "slug": "se/se-53-2016",
        "jenis": "SE",
        "nomor": "SE-53/PJ/2016",
        "title": "Petunjuk Pelaksanaan Pengenaan PBB Sektor Pertambangan Mineral dan Batubara",
        "tahun": 2016,
        "tanggal_diundangkan": "2016-11-25",
        "tanggal_berlaku": "2016-11-25",
        "status": "berlaku",
        "topik": ["PBB", "pertambangan", "mineral", "batubara", "petunjuk pelaksanaan"],
        "sektor": ["pertambangan_minerba"],
        "berlaku_untuk": ["PBB"],
        "ringkasan": "Petunjuk pelaksanaan pengenaan PBB sektor pertambangan mineral dan batubara.",
    },
    {
        "file": "UU_19_2000_ppsp.pdf",
        "slug": "uu/uu-19-2000",
        "jenis": "UU",
        "nomor": "UU-19/2000",
        "title": "Penagihan Pajak dengan Surat Paksa",
        "tahun": 2000,
        "tanggal_diundangkan": "2000-05-02",
        "tanggal_berlaku": "2000-05-02",
        "status": "berlaku",
        "topik": ["penagihan", "surat paksa", "PPSP"],
        "sektor": ["umum"],
        "berlaku_untuk": ["PBB", "PPh", "PPN"],
        "ringkasan": "Undang-Undang tentang Penagihan Pajak dengan Surat Paksa (PPSP).",
    },
]

EXTRACTED_DIR = "extracted"
OUTPUT_BASE = "../src/content/regulations"

def clean_text(text):
    """Clean extracted PDF text."""
    if not text:
        return ""
    # Remove excessive whitespace but preserve paragraph structure
    lines = text.split('\n')
    cleaned = []
    for line in lines:
        stripped = line.strip()
        if stripped:
            cleaned.append(stripped)
        elif cleaned and cleaned[-1] != '':
            cleaned.append('')
    return '\n'.join(cleaned)

def make_frontmatter(reg):
    """Generate YAML frontmatter."""
    lines = ['---']
    lines.append(f'title: "{reg["title"]}"')
    lines.append(f'nomor: "{reg["nomor"]}"')
    lines.append(f'jenis: "{reg["jenis"]}"')
    lines.append(f'tahun: {reg["tahun"]}')
    lines.append(f'tanggal_diundangkan: "{reg["tanggal_diundangkan"]}"')
    lines.append(f'tanggal_berlaku: "{reg["tanggal_berlaku"]}"')
    lines.append(f'status: "{reg["status"]}"')

    if reg.get("mencabut"):
        lines.append(f'mencabut:')
        for item in reg["mencabut"]:
            lines.append(f'  - "{item}"')
    if reg.get("dicabut_oleh"):
        lines.append(f'dicabut_oleh: "{reg["dicabut_oleh"]}"')
    if reg.get("mengubah"):
        lines.append(f'mengubah: "{reg["mengubah"]}"')
    if reg.get("diubah_oleh"):
        lines.append(f'diubah_oleh:')
        for item in reg["diubah_oleh"]:
            lines.append(f'  - "{item}"')

    lines.append(f'topik:')
    for t in reg["topik"]:
        lines.append(f'  - "{t}"')

    if reg.get("sektor"):
        lines.append(f'sektor:')
        for s in reg["sektor"]:
            lines.append(f'  - "{s}"')

    if reg.get("berlaku_untuk"):
        lines.append(f'berlaku_untuk:')
        for b in reg["berlaku_untuk"]:
            lines.append(f'  - "{b}"')

    if reg.get("dasar_hukum"):
        lines.append(f'dasar_hukum: "{reg["dasar_hukum"]}"')

    lines.append(f'ringkasan: "{reg["ringkasan"]}"')

    pdf_filename = reg["file"]
    encoded = pdf_filename.replace(' ', '%20').replace('~', '%7E')
    lines.append(f'sumber_pdf: "https://pbb.margondes.com/LinkedDocuments/{encoded}"')

    lines.append('---')
    return '\n'.join(lines)

def main():
    os.makedirs(OUTPUT_BASE, exist_ok=True)

    success = 0
    empty = 0

    for reg in REGULATIONS:
        slug = reg["slug"]
        pdf_file = reg["file"]
        txt_file = os.path.join(EXTRACTED_DIR, pdf_file.replace('.pdf', '.txt'))

        # Read extracted text
        body = ""
        if os.path.exists(txt_file):
            with open(txt_file, 'r', encoding='utf-8', errors='replace') as f:
                body = clean_text(f.read())

        if len(body.strip()) < 50:
            print(f"WARNING: Low text for {pdf_file} ({len(body)} chars)")
            body = f"*Teks peraturan ini sedang dalam proses ekstraksi dari PDF. Silakan unduh PDF asli untuk membaca isi lengkap.*\n\n[Download PDF]({reg.get('sumber_pdf', '')})"
            empty += 1
        else:
            success += 1

        # Generate markdown
        frontmatter = make_frontmatter(reg)

        # Create output path
        output_path = os.path.join(OUTPUT_BASE, f"{slug}.md")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(frontmatter)
            f.write('\n\n')
            f.write(body)
            f.write('\n')

    print(f"\nGenerated: {success + empty} files ({success} with text, {empty} with placeholder)")

if __name__ == "__main__":
    main()
